package com.Team11.Cluedo.board;

public enum TileType {
    SPAWN, KITCHEN, BALLROOM, HALLWAY,LOUNGE, CONSERVATORY, DININGROOM, CELLAR, BILLIARDROOM,
    LIBRARY, HALL,STUDY, SECRETPASSAGE,DOOR, BLANK
}
